import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { get_user } from "@/services/axiosMethods";
import { cookies } from "next/headers";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookiesStore = await cookies()
  const session_id = cookiesStore.get("session_id")?.value
  const user = await get_user(session_id)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <UserProvider initionalUser={user}>
          <Header/>
          {children}
          <Footer/>
        </UserProvider>
      </body>
    </html>
  );
}
